trigger:
  branches:
    include:
      - master
      - feature/*
pr:
  autoCancel: true
  branches:
    include:
      - master

pool:
  vmImage: 'windows-2019'

jobs:
- job: XamarinForms
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: ./netframework.yml
    parameters:
      Solution: 'xamarin-forms/**/*.csproj'
      BuildConfiguration: 'Release'
      DotNetVersion: '2.2.300'
